version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0-buster
      - image: chilledgeek/lilypond-docker:latest
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install --user -r requirements.txt

  test:
    docker:
      - image: circleci/python:3.8.0-buster
      - image: chilledgeek/lilypond-docker
    steps:
      - checkout
      - run:
          name: Test
          command: python -m unittest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
