version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: chilledgeek/lilypond-docker
    steps:
      - checkout
      - run:
          name: Set up workdir
          command: mkdir -p /workdir && chmod -R 777 /workdir

      - run:
          name: Install requirements
          command: pip install -r requirements.txt

  test:
    docker:
      - image: chilledgeek/lilypond-docker
    steps:
      - checkout
      - run:
          name: Test
          command: python -m unittest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
